# Generated by Django 2.1.4 on 2018-12-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('beschreibung', models.CharField(max_length=500)),
                ('bild', models.ImageField(upload_to='')),
                ('veroeffentlicht', models.DateTimeField(verbose_name='Datum Veröffentlicht')),
            ],
        ),
    ]
