# Generated by Django 2.1.4 on 2018-12-17 16:12

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='inhalt',
            field=froala_editor.fields.FroalaField(blank=True),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='beschreibung',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
