# Generated by Django 2.1.4 on 2019-01-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserLogin',
        ),
    ]
