# Generated by Django 2.1.4 on 2019-01-21 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190121_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='loggedInAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
            preserve_default=False,
        ),
    ]
