# Generated by Django 2.1.4 on 2019-02-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_category_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='str',
            new_name='word',
        ),
    ]
