# Generated by Django 2.1.4 on 2019-02-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190211_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Category'),
            preserve_default=False,
        ),
    ]
