# Generated by Django 2.1.4 on 2019-02-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_word_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=30)),
                ('date_played', models.DateTimeField(verbose_name='Date Played')),
            ],
        ),
    ]
