# Generated by Django 2.1.4 on 2019-02-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='amount_played',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
