# Generated by Django 2.1.7 on 2019-02-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_game_amount_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Player')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='login.Word')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='amount_played',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Player'),
        ),
    ]
