# Generated by Django 2.1.7 on 2019-02-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190218_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.CharField(max_length=30),
        ),
    ]
