# Generated by Django 2.1.7 on 2019-02-18 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190218_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_id',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='login.Player'),
        ),
    ]
