# Generated by Django 2.1.7 on 2019-02-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20190218_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_id',
        ),
    ]
