# Generated by Django 2.1.7 on 2019-02-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_remove_game_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='amount_played',
            field=models.IntegerField(default=0),
        ),
    ]
