# Generated by Django 2.1.7 on 2019-02-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20190221_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='konsonant',
            field=models.CharField(default='x', max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='amount_played',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
