# Generated by Django 2.1.7 on 2019-02-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20190222_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='konsonant',
            field=models.CharField(max_length=1),
        ),
    ]
