# Generated by Django 2.1.7 on 2019-02-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20190222_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konsonant', models.CharField(max_length=1)),
            ],
        ),
    ]
