# Generated by Django 2.1.7 on 2019-02-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
