# Generated by Django 2.1.7 on 2019-02-22 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='wort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wort', to='login.Word'),
        ),
    ]
