# Generated by Django 2.1.4 on 2019-02-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20190224_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerword',
            name='assigned_to_player',
        ),
    ]
