# Generated by Django 2.1.4 on 2019-02-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20190224_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='output',
            field=models.CharField(default='', max_length=200),
        ),
    ]
