# Generated by Django 2.1.4 on 2019-02-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_remove_game_times_guessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='amount_played',
            field=models.IntegerField(default=0),
        ),
    ]
