# Generated by Django 2.1.4 on 2019-02-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20190225_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='amount_played',
        ),
    ]
