# Generated by Django 2.1.4 on 2019-02-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_remove_game_amount_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='amount_played',
            field=models.IntegerField(default=0),
        ),
    ]
