# Generated by Django 2.1.4 on 2019-02-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_game_amount_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='test',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
