# Generated by Django 2.1.4 on 2019-02-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_game_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='amount_played',
            new_name='_amount_played',
        ),
    ]
