# Generated by Django 2.1.4 on 2019-02-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_auto_20190225_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='_amount_played',
            new_name='amount_played',
        ),
    ]
