# Generated by Django 2.1.4 on 2019-02-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_auto_20190225_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='answer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
