# Generated by Django 2.1.4 on 2019-02-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_word_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='answer',
        ),
        migrations.AddField(
            model_name='word',
            name='answer',
            field=models.ManyToManyField(to='login.Answer'),
        ),
    ]
