# Generated by Django 2.1.4 on 2019-02-25 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_auto_20190225_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='wort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Word'),
        ),
    ]
