# Generated by Django 2.1.4 on 2019-02-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='spielrunden',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
