# Generated by Django 2.1.4 on 2019-02-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_game_spielrunden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='spielrunden',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
