# Generated by Django 2.1.4 on 2019-03-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0037_auto_20190301_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='spielrunden',
            field=models.IntegerField(default=0),
        ),
    ]
